server:
  port: 8000
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9091/validateUser
spring:
  application:
    name: OrderService
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:greetingDb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS