server:
  port: 8000
spring:
  application:
    name: PrimaryService
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:greetingDb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
 client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.102:8761/eureka
 
  
